# Generated by Django 3.0.6 on 2020-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='posted_msg',
            field=models.TextField(default=''),
        ),
    ]
